const translations = {
    "ar": {
        "home_title": "مخيم istanova الصيفي: مغامرتك تبدأ هنا!",
        "home_slogan_1": "مرح، مغامرة، وذكريات لا تُنسى في قلب شيلا، اسطنبول!",
        "home_slogan_2": "استرخِ على شاطئ البحر، انطلق في أنشطة مثيرة، والتقِ بأصدقاء جدد!",
        "home_slogan_3": "أيام مليئة بالضحك والفرح، وليالي ساحرة تحت النجوم!",
        "home_about_us_heading": "عن مخيمنا",
        "home_about_us_text": "مخيم istanova الصيفي هو وجهتك المثالية لقضاء 6 أيام و5 ليالٍ مليئة بالمرح والإثارة على شاطئ البحر مباشرة في شيلا، اسطنبول. نقدم تجربة فريدة للبالغين من 18 إلى 45 عامًا، سواء كنت فردًا، زوجين، أصدقاء، أو مجموعة. استعد لمغامرة لا تُنسى حيث يلتقي الاسترخاء بالنشاط، وتصنع ذكريات تدوم مدى الحياة.",
        "home_activities_heading": "برنامج الأنشطة اليومية والمغامرات",
        "home_activities_intro": "جهز نفسك لأيام مليئة بالإثارة والضحك، ولن تنسى أن تحضر ابتسامتك وحماسك! برنامجنا مصمم ليُنسيك الروتين ويغمرك بالبهجة:",
        "home_activity_1": "أنشطة صباحية منعشة: ابدأ يومك بنشاطات ترفيهية خفيفة على الشاطئ.",
        "home_activity_2": "كرة الطائرة وكرة القدم الشاطئية: تحديات ودية ومرح غير محدود.",
        "home_activity_3": "مغامرة الرافتنج النهرية: انطلق في رحلة مثيرة عبر الأنهار الجارية.",
        "home_activity_4": "رحلة سفاري بالدراجات النارية (ATV): استكشف المناظر الطبيعية الخلابة.",
        "home_activity_5": "تجربة الزبلاين: حلق في الهواء واستمتع بالمناظر من الأعلى.",
        "home_activity_6": "حفلات شواء مسائية: تذوق أشهى الأطعمة تحت النجوم.",
        "home_activity_7": "احتفالات ليلية وألعاب نارية: ليالٍ لا تُنسى من البهجة والاحتفال.",
        "home_activity_8": "أنشطة تعارف ومسابقات وهدايا: كوّن صداقات جديدة واربح جوائز قيمة.",
        "home_activity_9": "تحديات وألعاب تحفيزية: اختبر مهاراتك واستمتع بروح المنافسة.",
        "home_schedule_heading": "جدول الرحلة (15 - 20 يوليو 2025)",
        "home_schedule_day_1": "اليوم الأول: الوصول والتسكين، التعارف، حفل شواء ترحيبي.",
        "home_schedule_day_2": "اليوم الثاني: أنشطة شاطئية صباحية، كرة طائرة وقدم، أنشطة مسائية ومسابقات.",
        "home_schedule_day_3": "اليوم الثالث: رحلة رافتنج نهرية، أنشطة مسائية واحتفال.",
        "home_schedule_day_4": "اليوم الرابع: رحلة سفاري ATV، زبلاين، حفلة ليلية وألعاب نارية.",
        "home_schedule_day_5": "اليوم الخامس: أنشطة حرة على الشاطئ، مسابقات ختامية، حفل وداع.",
        "home_schedule_day_6": "اليوم السادس: وجبة الإفطار، تسجيل الخروج، العودة إلى اسطنبول.",
        "home_price_heading": "السعر يشمل كل شيء!",
        "home_price_text": "فقط **500 دولار للفرد**! هذا السعر يشمل كل ما تحتاجه لتجربة مريحة وممتعة:",
        "home_price_included_1": "الإقامة لمدة 5 ليالٍ و6 أيام.",
        "home_price_included_2": "جميع الوجبات والمشروبات طوال الوقت (بما في ذلك الشاي التركي الأصيل).",
        "home_price_included_3": "جميع الأنشطة والفعاليات المذكورة.",
        "home_price_included_4": "النقل من وإلى اسطنبول وجميع التنقلات الداخلية.",
        "home_price_included_5": "إنترنت و كهرباء في المخيم.",
        "home_price_included_6": "تصوير احترافي وتصوير بالدرون لتوثيق لحظاتكم.",
        "home_booking_cta": "احجز مكانك الآن!",
        "home_what_to_bring_heading": "ماذا تحضر معك؟",
        "home_what_to_bring_text": "لتعزيز تجربتك، لا تنسَ إحضار هذه الأساسيات:",
        "home_item_1": "نظارة شمسية: للحماية من أشعة الشمس.",
        "home_item_2": "قبعة: للحماية من الشمس.",
        "home_item_3": "واقي شمسي: للحفاظ على بشرتك آمنة.",
        "home_item_4": "ملابس سباحة: للاستمتاع بالبحر وأنشطة الماء.",
        "home_item_5": "أحذية رياضية مريحة: للمغامرات والأنشطة.",
        "home_item_6": "ملابس خفيفة ومريحة: لأجواء المخيم.",
        "home_item_7": "جاكيت خفيف: لليالي الباردة.",
        "home_item_8": "كاميرا شخصية (اختياري): إذا كنت ترغب في التقاط صورك الخاصة.",
        "home_item_9": "ابتسامتك وروح المغامرة: الأهم من كل شيء!",
        "footer_address": "العنوان: اسطنبول، الفاتح، مقابل ترام واي يوسف باشا، رقم 42، مكتب رقم 8",
        "footer_phone": "رقم الهاتف: +905457307235",
        "footer_email": "البريد الإلكتروني: unitedhr8@gmail.com",
        "footer_company": "© 2025 istanova. جميع الحقوق محفوظة.",
        "nav_home": "الرئيسية",
        "nav_booking": "الحجز والدفع",
        "nav_contact": "تواصل معنا",
        "terms_and_conditions_heading": "الشروط والأحكام",
        "terms_and_conditions_intro": "يرجى قراءة الشروط والأحكام التالية بعناية قبل إتمام عملية الحجز. موافقتك على الحجز تعني موافقتك على هذه الشروط:",
        "term_1_title": "الفئة العمرية",
        "term_1_text": "المخيم مخصص حصريًا للفئة العمرية من 18 إلى 45 عامًا. لن يتم قبول أي حجوزات خارج هذا النطاق العمري. في حال الحجز لعمر غير مطابق، سيتم إلغاء الحجز دون استرداد المبلغ المدفوع.",
        "term_2_title": "سياسة الحجز والدفع",
        "term_2_text": "يتطلب تأكيد الحجز دفع كامل المبلغ. سيتم توضيح خيارات الدفع المتاحة في صفحة الحجز.",
        "term_3_title": "سياسة الإلغاء",
        "term_3_text": "في حال الإلغاء قبل 30 يومًا من تاريخ الرحلة، يتم استرداد 70% من المبلغ المدفوع. في حال الإلغاء قبل 15 يومًا، يتم استرداد 50% من المبلغ المدفوع. لا يوجد استرداد للمبلغ في حال الإلغاء قبل أقل من 15 يومًا من تاريخ الرحلة.",
        "term_4_title": "المسؤولية",
        "term_4_text": "شركة istanova غير مسؤولة عن أي ممتلكات شخصية مفقودة أو تالفة. جميع الأنشطة تتم على مسؤولية المشارك الشخصية، مع التزامنا باتخاذ جميع تدابير السلامة اللازمة.",
        "term_5_title": "السلوك",
        "term_5_text": "يجب على جميع المشاركين الالتزام بقواعد المخيم والسلوكيات العامة. تحتفظ إدارة المخيم بالحق في طرد أي مشارك يخالف هذه القواعد دون استرداد المبلغ المدفوع.",
        "term_6_title": "التصوير",
        "term_6_text": "بالموافقة على هذه الشروط، يوافق المشارك على استخدام الصور ومقاطع الفيديو الملتقطة خلال المخيم لأغراض ترويجية للشركة.",
        "term_7_title": "الاحتياجات الخاصة",
        "term_7_text": "يرجى إبلاغنا مسبقًا بأي احتياجات خاصة أو حساسية تجاه الطعام لنتخذ الترتيبات اللازمة.",
        "term_8_title": "تغيير البرنامج",
        "term_8_text": "تحتفظ إدارة المخيم بالحق في تعديل برنامج الأنشطة أو الجدول الزمني في حال حدوث ظروف خارجة عن إرادتنا (مثل سوء الأحوال الجوية) لضمان سلامة وراحة المشاركين.",
        "term_agree": "أوافق على الشروط والأحكام",
        "booking_form_heading": "نموذج الحجز والدفع",
        "booking_form_intro": "املأ النموذج أدناه لتأكيد حجزك. يرجى التأكد من صحة البيانات.",
        "booking_num_participants": "عدد المشاركين:",
        "booking_num_participants_placeholder": "اختر عدد المشاركين",
        "booking_relationship": "العلاقة:",
        "booking_relationship_couple": "زوجين",
        "booking_relationship_friends": "أصدقاء",
        "booking_participant_name": "اسم المشارك",
        "booking_participant_age": "تاريخ ميلاد المشارك",
        "booking_participant_gender": "جنس المشارك",
        "booking_participant_male": "ذكر",
        "booking_participant_female": "أنثى",
        "booking_participant_nationality": "جنسية المشارك",
        "booking_phone_number": "رقم الهاتف",
        "booking_phone_code": "رمز الدولة",
        "booking_email": "البريد الإلكتروني",
        "booking_price_per_person": "سعر الفرد:",
        "booking_discount": "الخصم:",
        "booking_total_price": "المبلغ الإجمالي:",
        "booking_final_price": "المبلغ النهائي للدفع:",
        "booking_pay_now": "ادفع الآن",
        "booking_submit_btn": "تأكيد الحجز",
        "booking_age_error": "عذراً، يجب أن يكون عمر المشارك بين 18 و 45 عامًا. نتمنى أن نراك في رحلات قادمة!",
        "booking_terms_checkbox_text": "أوافق على ",
        "booking_terms_link": "الشروط والأحكام",
        "booking_terms_confirm_message": "يجب قراءة الشروط والأحكام جيداً والموافقة عليها للمتابعة.",
        "contact_heading": "تواصل معنا",
        "contact_text": "يسعدنا الإجابة على جميع استفساراتكم. يمكنكم التواصل معنا عبر الطرق التالية:",
        "contact_form_heading": "أو أرسل لنا رسالة",
        "contact_name": "اسمك الكامل",
        "contact_email": "بريدك الإلكتروني",
        "contact_message": "رسالتك",
        "contact_send": "إرسال الرسالة",
        "payment_method_bank_transfer": "تحويل بنكي",
        "payment_method_cash": "دفع كاش في المكتب",
        "payment_method_paypal": "باي بال",
        "payment_method_instapay": "انستا باي",
        "payment_method_vodafone_cash": "فودافون كاش",
        "payment_method_papara": "بابارا",
        "payment_method_revolut": "ريفولت",
        "bank_details_heading": "تفاصيل التحويل البنكي:",
        "bank_account_name": "اسم صاحب الحساب:",
        "bank_account_number": "رقم الحساب:",
        "bank_swift_code": "رمز سويفت (SWIFT Code):",
        "vodafone_cash_details_heading": "تفاصيل فودافون كاش:",
        "vodafone_cash_number": "رقم فودافون كاش:",
        "male_label": "المشارك",
        "female_label": "المشاركة",
        "participant_label": "المشارك",
        "couple_male_label": "الزوج",
        "couple_female_label": "الزوجة",
        "payment_gateway_note": "مدعوم بواسطة",
        "payment_methods_heading": "طرق الدفع",
        "choose_relation_placeholder": "اختر العلاقة",
    },
    "en": {
        "home_title": "istanova Summer Camp: Your Adventure Starts Here!",
        "home_slogan_1": "Fun, adventure, and unforgettable memories in the heart of Şile, Istanbul!",
        "home_slogan_2": "Relax on the beach, embark on exciting activities, and meet new friends!",
        "home_slogan_3": "Days full of laughter and joy, and magical nights under the stars!",
        "home_about_us_heading": "About Our Camp",
        "home_about_us_text": "istanova Summer Camp is your perfect destination for 6 days and 5 nights of fun and excitement right on the beach in Şile, Istanbul. We offer a unique experience for adults aged 18 to 45, whether you are an individual, a couple, friends, or a group. Get ready for an unforgettable adventure where relaxation meets activity, and memories are made to last a lifetime.",
        "home_activities_heading": "Daily Activities and Adventure Program",
        "home_activities_intro": "Get ready for days full of excitement and laughter, and don't forget to bring your smile and enthusiasm! Our program is designed to make you forget routine and immerse you in joy:",
        "home_activity_1": "Refreshing Morning Activities: Start your day with light recreational activities on the beach.",
        "home_activity_2": "Beach Volleyball and Football: Friendly challenges and unlimited fun.",
        "home_activity_3": "River Rafting Adventure: Embark on an exciting journey through flowing rivers.",
        "home_activity_4": "ATV Safari Trip: Explore breathtaking natural landscapes.",
        "home_activity_5": "Zipline Experience: Soar through the air and enjoy the views from above.",
        "home_activity_6": "Evening BBQ Parties: Savor delicious food under the stars.",
        "home_activity_7": "Night Celebrations and Fireworks: Unforgettable nights of joy and celebration.",
        "home_activity_8": "Socializing Activities, Competitions, and Gifts: Make new friends and win valuable prizes.",
        "home_activity_9": "Motivational Challenges and Games: Test your skills and enjoy the spirit of competition.",
        "home_schedule_heading": "Trip Schedule (July 15 - 20, 2025)",
        "home_schedule_day_1": "Day 1: Arrival and Check-in, Socializing, Welcome BBQ Party.",
        "home_schedule_day_2": "Day 2: Morning Beach Activities, Volleyball and Football, Evening Activities and Competitions.",
        "home_schedule_day_3": "Day 3: River Rafting Trip, Evening Activities and Celebration.",
        "home_schedule_day_4": "Day 4: ATV Safari, Zipline, Night Party and Fireworks.",
        "home_schedule_day_5": "Day 5: Free Beach Activities, Final Competitions, Farewell Party.",
        "home_schedule_day_6": "Day 6: Breakfast, Check-out, Return to Istanbul.",
        "home_price_heading": "Price Includes Everything!",
        "home_price_text": "Only **$500 per person**! This price includes everything you need for a comfortable and enjoyable experience:",
        "home_price_included_1": "Accommodation for 5 nights and 6 days.",
        "home_price_included_2": "All meals and drinks throughout (including authentic Turkish tea).",
        "home_price_included_3": "All listed activities and events.",
        "home_price_included_4": "Transportation to and from Istanbul and all internal transfers.",
        "home_price_included_5": "Internet and electricity at the camp.",
        "home_price_included_6": "Professional photography and drone photography to capture your moments.",
        "home_booking_cta": "Book Your Spot Now!",
        "home_what_to_bring_heading": "What to Bring?",
        "home_what_to_bring_text": "To enhance your experience, don't forget to bring these essentials:",
        "home_item_1": "Sunglasses: For sun protection.",
        "home_item_2": "Hat: For sun protection.",
        "home_item_3": "Sunscreen: To keep your skin safe.",
        "home_item_4": "Swimwear: To enjoy the sea and water activities.",
        "home_item_5": "Comfortable sports shoes: For adventures and activities.",
        "home_item_6": "Light and comfortable clothing: For camp atmosphere.",
        "home_item_7": "Light jacket: For cooler nights.",
        "home_item_8": "Personal camera (optional): If you want to take your own photos.",
        "home_item_9": "Your smile and adventurous spirit: The most important of all!",
        "footer_address": "Address: Istanbul, Fatih, Opposite Yusufpaşa Tramway, No. 42, Office No. 8",
        "footer_phone": "Phone: +905457307235",
        "footer_email": "Email: unitedhr8@gmail.com",
        "footer_company": "© 2025 istanova. All rights reserved.",
        "nav_home": "Home",
        "nav_booking": "Book & Pay",
        "nav_contact": "Contact Us",
        "terms_and_conditions_heading": "Terms and Conditions",
        "terms_and_conditions_intro": "Please read the following terms and conditions carefully before completing your booking. Your booking implies your agreement to these terms:",
        "term_1_title": "Age Group",
        "term_1_text": "The camp is exclusively for individuals aged 18 to 45 years. No bookings outside this age range will be accepted. In case of booking for a non-compliant age, the booking will be cancelled without refund.",
        "term_2_title": "Booking and Payment Policy",
        "term_2_text": "Full payment is required to confirm your booking. Available payment options will be detailed on the booking page.",
        "term_3_title": "Cancellation Policy",
        "term_3_text": "If cancelled 30 days before the trip date, 70% of the amount paid will be refunded. If cancelled 15 days before, 50% of the amount paid will be refunded. No refund will be issued if cancelled less than 15 days before the trip date.",
        "term_4_title": "Responsibility",
        "term_4_text": "istanova company is not responsible for any lost or damaged personal belongings. All activities are at the participant's personal risk, with our commitment to taking all necessary safety measures.",
        "term_5_title": "Conduct",
        "term_5_text": "All participants must adhere to camp rules and general conduct. Camp management reserves the right to expel any participant who violates these rules without refund.",
        "term_6_title": "Photography",
        "term_6_text": "By agreeing to these terms, the participant agrees to the use of photos and videos taken during the camp for promotional purposes of the company.",
        "term_7_title": "Special Needs",
        "term_7_text": "Please inform us in advance of any special needs or food allergies so we can make the necessary arrangements.",
        "term_8_title": "Program Changes",
        "term_8_text": "Camp management reserves the right to modify the activity program or schedule in case of circumstances beyond our control (such as bad weather) to ensure the safety and comfort of participants.",
        "term_agree": "I agree to the Terms and Conditions",
        "booking_form_heading": "Booking and Payment Form",
        "booking_form_intro": "Fill out the form below to confirm your booking. Please ensure the accuracy of the data.",
        "booking_num_participants": "Number of Participants:",
        "booking_num_participants_placeholder": "Select number of participants",
        "booking_relationship": "Relationship:",
        "booking_relationship_couple": "Couple",
        "booking_relationship_friends": "Friends",
        "booking_participant_name": "Participant Name",
        "booking_participant_age": "Participant Date of Birth",
        "booking_participant_gender": "Participant Gender",
        "booking_participant_male": "Male",
        "booking_participant_female": "Female",
        "booking_participant_nationality": "Participant Nationality",
        "booking_phone_number": "Phone Number",
        "booking_phone_code": "Country Code",
        "booking_email": "Email Address",
        "booking_price_per_person": "Price per person:",
        "booking_discount": "Discount:",
        "booking_total_price": "Total Price:",
        "booking_final_price": "Final Amount to Pay:",
        "booking_pay_now": "Pay Now",
        "booking_submit_btn": "Confirm Booking",
        "booking_age_error": "Sorry, participant's age must be between 18 and 45 years. We hope to see you on future trips!",
        "booking_terms_checkbox_text": "I agree to the ",
        "booking_terms_link": "Terms and Conditions",
        "booking_terms_confirm_message": "You must read and agree to the terms and conditions carefully to proceed.",
        "contact_heading": "Contact Us",
        "contact_text": "We are happy to answer all your inquiries. You can contact us through the following methods:",
        "contact_form_heading": "Or Send Us a Message",
        "contact_name": "Your Full Name",
        "contact_email": "Your Email",
        "contact_message": "Your Message",
        "contact_send": "Send Message",
        "payment_method_bank_transfer": "Bank Transfer",
        "payment_method_cash": "Cash Payment at Office",
        "payment_method_paypal": "PayPal",
        "payment_method_instapay": "InstaPay",
        "payment_method_vodafone_cash": "Vodafone Cash",
        "payment_method_papara": "Papara",
        "payment_method_revolut": "Revolut",
        "bank_details_heading": "Bank Transfer Details:",
        "bank_account_name": "Account Holder Name:",
        "bank_account_number": "Account Number:",
        "bank_swift_code": "SWIFT Code:",
        "vodafone_cash_details_heading": "Vodafone Cash Details:",
        "vodafone_cash_number": "Vodafone Cash Number:",
        "male_label": "Participant",
        "female_label": "Participant",
        "participant_label": "Participant",
        "couple_male_label": "Husband",
        "couple_female_label": "Wife",
        "payment_gateway_note": "Powered by",
        "payment_methods_heading": "Payment Methods",
        "choose_relation_placeholder": "Select relationship",
    },
    "tr": {
        "home_title": "istanova Yaz Kampı: Maceranız Burada Başlıyor!",
        "home_slogan_1": "Şile, İstanbul'un kalbinde eğlence, macera ve unutulmaz anılar!",
        "home_slogan_2": "Plajda rahatlayın, heyecan verici aktivitelere katılın ve yeni arkadaşlar edinin!",
        "home_slogan_3": "Kahkaha ve neşe dolu günler, yıldızların altında büyülü geceler!",
        "home_about_us_heading": "Kampımız Hakkında",
        "home_about_us_text": "istanova Yaz Kampı, Şile, İstanbul'da denizin hemen kenarında, eğlence ve heyecan dolu 6 gün 5 gece geçirmek için mükemmel bir destinasyondur. İster bireysel, ister çift, ister arkadaş grubu olun, 18 ila 45 yaş arası yetişkinler için eşsiz bir deneyim sunuyoruz. Rahatlamanın aktiviteyle buluştuğu, ömür boyu sürecek anıların yaratıldığı unutulmaz bir maceraya hazır olun.",
        "home_activities_heading": "Günlük Aktiviteler ve Macera Programı",
        "home_activities_intro": "Kendinizi heyecan ve kahkaha dolu günlere hazırlayın, gülümsemenizi ve coşkunuzu getirmeyi unutmayın! Programımız rutini unutturup sizi neşeyle doldurmak için tasarlandı:",
        "home_activity_1": "Canlandırıcı Sabah Aktiviteleri: Güne plajda hafif eğlence aktiviteleriyle başlayın.",
        "home_activity_2": "Plaj Voleybolu ve Futbolu: Dostça mücadeleler ve sınırsız eğlence.",
        "home_activity_3": "Nehir Rafting Macerası: Coşkulu nehirlerde heyecan verici bir yolculuğa çıkın.",
        "home_activity_4": "ATV Safari Turu: Nefes kesici doğal manzaraları keşfedin.",
        "home_activity_5": "Zipline Deneyimi: Havada süzülün ve yukarıdan manzaraların tadını çıkarın.",
        "home_activity_6": "Akşam Barbekü Partileri: Yıldızların altında lezzetli yemeklerin tadını çıkarın.",
        "home_activity_7": "Gece Kutlamaları ve Havai Fişekler: Neşe ve kutlama dolu unutulmaz geceler.",
        "home_activity_8": "Tanışma Aktiviteleri, Yarışmalar ve Hediyeler: Yeni arkadaşlar edinin ve değerli ödüller kazanın.",
        "home_activity_9": "Motivasyonel Yarışmalar ve Oyunlar: Becerilerinizi test edin ve rekabet ruhunun tadını çıkarın.",
        "home_schedule_heading": "Gezi Takvimi (15 - 20 Temmuz 2025)",
        "home_schedule_day_1": "1. Gün: Varış ve Yerleşme, Tanışma, Karşılama Barbekü Partisi.",
        "home_schedule_day_2": "2. Gün: Sabah Plaj Aktiviteleri, Voleybol ve Futbol, Akşam Aktiviteleri ve Yarışmalar.",
        "home_schedule_day_3": "3. Gün: Nehir Rafting Gezisi, Akşam Aktiviteleri ve Kutlama.",
        "home_schedule_day_4": "4. Gün: ATV Safari, Zipline, Gece Partisi ve Havai Fişekler.",
        "home_schedule_day_5": "5. Gün: Serbest Plaj Aktiviteleri, Final Yarışmaları, Veda Partisi.",
        "home_schedule_day_6": "6. Gün: Kahvaltı, Çıkış, İstanbul'a Dönüş.",
        "home_price_heading": "Fiyata Her Şey Dahil!",
        "home_price_text": "Sadece **kişi başı 500 $**! Bu fiyat, konforlu ve keyifli bir deneyim için ihtiyacınız olan her şeyi içerir:",
        "home_price_included_1": "5 gece 6 gün konaklama.",
        "home_price_included_2": "Tüm öğünler ve içecekler (gerçek Türk çayı dahil).",
        "home_price_included_3": "Listelenen tüm aktiviteler ve etkinlikler.",
        "home_price_included_4": "İstanbul'a ve İstanbul'dan ulaşım ile tüm iç transferler.",
        "home_price_included_5": "Kamp alanında internet ve elektrik.",
        "home_price_included_6": "Anlarınızı ölümsüzleştirmek için profesyonel fotoğraf çekimi ve dron çekimi.",
        "home_booking_cta": "Yerinizi Şimdi Ayırtın!",
        "home_what_to_bring_heading": "Yanınızda Ne Getirmelisiniz?",
        "home_what_to_bring_text": "Deneyiminizi geliştirmek için bu temel eşyaları getirmeyi unutmayın:",
        "home_item_1": "Güneş gözlüğü: Güneşten korunmak için.",
        "home_item_2": "Şapka: Güneşten korunmak için.",
        "home_item_3": "Güneş kremi: Cildinizi güvende tutmak için.",
        "home_item_4": "Mayo: Denizin ve su aktivitelerinin tadını çıkarmak için.",
        "home_item_5": "Rahat spor ayakkabıları: Maceralar ve aktiviteler için.",
        "home_item_6": "Hafif ve rahat kıyafetler: Kamp ortamı için.",
        "home_item_7": "Hafif bir ceket: Serin geceler için.",
        "home_item_8": "Kişisel kamera (isteğe bağlı): Kendi fotoğraflarınızı çekmek isterseniz.",
        "home_item_9": "Gülümsemeniz ve macera ruhunuz: Her şeyden önemlisi!",
        "footer_address": "Adres: İstanbul, Fatih, Yusufpaşa Tramvay Durağı Karşısı, No: 42, Ofis No: 8",
        "footer_phone": "Telefon: +905457307235",
        "footer_email": "E-posta: unitedhr8@gmail.com",
        "footer_company": "© 2025 istanova. Tüm Hakları Saklıdır.",
        "nav_home": "Ana Sayfa",
        "nav_booking": "Rezervasyon ve Ödeme",
        "nav_contact": "Bize Ulaşın",
        "terms_and_conditions_heading": "Şartlar ve Koşullar",
        "terms_and_conditions_intro": "Rezervasyon işlemini tamamlamadan önce lütfen aşağıdaki şartları ve koşulları dikkatlice okuyunuz. Rezervasyonunuz, bu şartları kabul ettiğiniz anlamına gelir:",
        "term_1_title": "Yaş Grubu",
        "term_1_text": "Kamp sadece 18 ila 45 yaş arası bireyler için özeldir. Bu yaş aralığı dışındaki hiçbir rezervasyon kabul edilmeyecektir. Yaş uyumsuzluğu durumunda, rezervasyon iadesiz olarak iptal edilecektir.",
        "term_2_title": "Rezervasyon ve Ödeme Politikası",
        "term_2_text": "Rezervasyonunuzu onaylamak için tam ödeme gereklidir. Mevcut ödeme seçenekleri rezervasyon sayfasında detaylandırılacaktır.",
        "term_3_title": "İptal Politikası",
        "term_3_text": "Gezi tarihinden 30 gün önce iptal edilmesi durumunda, ödenen miktarın %70'i iade edilecektir. 15 gün önce iptal edilmesi durumunda, ödenen miktarın %50'si iade edilecektir. Gezi tarihinden 15 günden daha az bir süre kala yapılan iptallerde iade yapılmayacaktır.",
        "term_4_title": "Sorumluluk",
        "term_4_text": "istanova şirketi, kaybolan veya hasar gören kişisel eşyalardan sorumlu değildir. Tüm aktiviteler katılımcının kişisel sorumluluğundadır, ancak tüm gerekli güvenlik önlemlerini alma taahhüdümüz vardır.",
        "term_5_title": "Davranış",
        "term_5_text": "Tüm katılımcılar kamp kurallarına ve genel davranışlara uymalıdır. Kamp yönetimi, bu kuralları ihlal eden herhangi bir katılımcıyı iade yapmaksızın kamptan çıkarma hakkını saklı tutar.",
        "term_6_title": "Fotoğraf Çekimi",
        "term_6_text": "Bu şartları kabul ederek, katılımcı kamp sırasında çekilen fotoğraf ve videoların şirketin tanıtım amaçlı kullanılmasına izin verir.",
        "term_7_title": "Özel İhtiyaçlar",
        "term_7_text": "Gerekli düzenlemeleri yapabilmemiz için özel ihtiyaçlarınızı veya gıda alerjilerinizi önceden bize bildirmenizi rica ederiz.",
        "term_8_title": "Program Değişiklikleri",
        "term_8_text": "Kamp yönetimi, katılımcıların güvenliğini ve konforunu sağlamak amacıyla kontrolümüz dışındaki koşullar (örneğin kötü hava koşulları) durumunda aktivite programını veya takvimi değiştirme hakkını saklı tutar.",
        "term_agree": "Şartlar ve Koşulları kabul ediyorum",
        "booking_form_heading": "Rezervasyon ve Ödeme Formu",
        "booking_form_intro": "Rezervasyonunuzu onaylamak için aşağıdaki formu doldurun. Lütfen verilerin doğruluğundan emin olun.",
        "booking_num_participants": "Katılımcı Sayısı:",
        "booking_num_participants_placeholder": "Katılımcı sayısını seçin",
        "booking_relationship": "İlişki:",
        "booking_relationship_couple": "Çift",
        "booking_relationship_friends": "Arkadaşlar",
        "booking_participant_name": "Katılımcı Adı",
        "booking_participant_age": "Katılımcı Doğum Tarihi",
        "booking_participant_gender": "Katılımcı Cinsiyeti",
        "booking_participant_male": "Erkek",
        "booking_participant_female": "Kadın",
        "booking_participant_nationality": "Katılımcı Uyruğu",
        "booking_phone_number": "Telefon Numarası",
        "booking_phone_code": "Ülke Kodu",
        "booking_email": "E-posta Adresi",
        "booking_price_per_person": "Kişi Başı Fiyat:",
        "booking_discount": "İndirim:",
        "booking_total_price": "Toplam Fiyat:",
        "booking_final_price": "Ödenecek Son Miktar:",
        "booking_pay_now": "Şimdi Öde",
        "booking_submit_btn": "Rezervasyonu Onayla",
        "booking_age_error": "Üzgünüz, katılımcının yaşı 18 ile 45 arasında olmalıdır. Sizi gelecekteki gezilerde görmeyi umuyoruz!",
        "booking_terms_checkbox_text": " kabul ediyorum",
        "booking_terms_link": "Şartlar ve Koşulları",
        "booking_terms_confirm_message": "Devam etmek için şartlar ve koşulları dikkatlice okuyup kabul etmelisiniz.",
        "contact_heading": "Bize Ulaşın",
        "contact_text": "Tüm sorularınızı yanıtlamaktan mutluluk duyarız. Aşağıdaki yöntemlerle bize ulaşabilirsiniz:",
        "contact_form_heading": "Veya Bize Bir Mesaj Gönderin",
        "contact_name": "Adınız Soyadınız",
        "contact_email": "E-posta Adresiniz",
        "contact_message": "Mesajınız",
        "contact_send": "Mesaj Gönder",
        "payment_method_bank_transfer": "Banka Havalesi",
        "payment_method_cash": "Ofiste Nakit Ödeme",
        "payment_method_paypal": "PayPal",
        "payment_method_instapay": "InstaPay",
        "payment_method_vodafone_cash": "Vodafone Cash",
        "payment_method_papara": "Papara",
        "payment_method_revolut": "Revolut",
        "bank_details_heading": "Banka Havalesi Detayları:",
        "bank_account_name": "Hesap Sahibi Adı:",
        "bank_account_number": "Hesap Numarası:",
        "bank_swift_code": "SWIFT Kodu:",
        "vodafone_cash_details_heading": "Vodafone Nakit Detayları:",
        "vodafone_cash_number": "Vodafone Nakit Numarası:",
        "male_label": "Katılımcı",
        "female_label": "Katılımcı",
        "participant_label": "Katılımcı",
        "couple_male_label": "Eş (Erkek)",
        "couple_female_label": "Eş (Kadın)",
        "payment_gateway_note": "Tarafından desteklenmektedir",
        "payment_methods_heading": "Ödeme Yöntemleri",
        "choose_relation_placeholder": "İlişki seçin",
    }
};